name: Nightly Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build DLL
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Nightly
      uses: actions/upload-artifact@v4
      with:
        name: "Manganese-Nightly-${GITHUB_SHA::7}"
        path: |
          D:\a\Permdog99\Manganese\out\build\x64-Release\Manganese.dll
          D:\a\Permdog99\Manganese\LICENSE.md
          D:\a\Permdog99\Manganese\README.md
          D:\a\Permdog99\Manganese\CREDITS.md
